//! # Error Definitions
//!
//! This module contains all error types used by the batch swap router program.
//! Errors are defined using Anchor's `#[error_code]` attribute, which automatically
//! generates error codes and error handling code.
//!
//! ## Error Types
//!
//! All errors are defined in the `ErrorCode` enum. Each error has:
//! - A unique error code (automatically generated by Anchor)
//! - A descriptive error message
//! - Documentation explaining when the error occurs
//!
//! ## Error Handling
//!
//! Errors are returned using Anchor's `Result<T>` type. When an error occurs:
//! - The transaction is reverted
//! - The error code is returned to the client
//! - The error message is available for debugging
//!
//! ## Error Categories
//!
//! - **Validation Errors**: Input validation failures
//! - **Account Errors**: Account-related errors
//! - **Transfer Errors**: Token transfer failures
//! - **State Errors**: Program state errors

use anchor_lang::prelude::*;

/// Error codes for the batch swap router program
///
/// This enum defines all possible errors that can occur during program execution.
/// Each error has a unique code and a descriptive message.
///
/// # Error Codes
///
/// Anchor automatically assigns error codes starting from 6000. Each error
/// in this enum gets a unique code that can be used for error handling and
/// debugging.
///
/// # Error Messages
///
/// Each error has a descriptive message that explains what went wrong.
/// These messages are useful for debugging and user feedback.
///
/// # Usage
///
/// Errors are returned using Anchor's `Result<T>` type:
///
/// ```rust,ignore
/// require!(condition, ErrorCode::SomeError);
/// ```
///
/// # Error Handling
///
/// When an error occurs:
/// - The transaction is immediately reverted
/// - All account changes are rolled back
/// - The error code is returned to the client
/// - The error message is logged (if logging is enabled)
#[error_code]
pub enum ErrorCode {
    /// Empty swaps array error
    ///
    /// This error occurs when a batch swap is attempted with an empty
    /// array of swaps. At least one swap must be provided.
    ///
    /// # When This Error Occurs
    ///
    /// - User provides an empty array to `batch_swap` instruction
    /// - Array is empty after filtering or validation
    ///
    /// # How to Fix
    ///
    /// - Ensure at least one swap is provided in the batch
    /// - Check that swaps are not filtered out before calling the instruction
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// // This will cause EmptySwaps error
    /// batch_swap(ctx, vec![])?;
    ///
    /// // This is correct
    /// batch_swap(ctx, vec![SwapParams { ... }])?;
    /// ```
    #[msg("Empty swaps array")]
    EmptySwaps,
    
    /// Too many swaps error
    ///
    /// This error occurs when a batch swap is attempted with more than
    /// the maximum allowed number of swaps per batch.
    ///
    /// # When This Error Occurs
    ///
    /// - User provides more than MAX_BATCH_SIZE (10) swaps
    /// - Array exceeds the batch size limit
    ///
    /// # How to Fix
    ///
    /// - Reduce the number of swaps to MAX_BATCH_SIZE or less
    /// - Split large batches into multiple transactions
    ///
    /// # Limits
    ///
    /// - Maximum swaps per batch: MAX_BATCH_SIZE (10)
    /// - This limit prevents DoS attacks and transaction size issues
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// // This will cause TooManySwaps error if swaps.len() > 10
    /// batch_swap(ctx, swaps)?;
    ///
    /// // Split into multiple batches
    /// batch_swap(ctx, swaps[..10].to_vec())?;
    /// batch_swap(ctx, swaps[10..].to_vec())?;
    /// ```
    #[msg("Too many swaps (max 10 per batch)")]
    TooManySwaps,
    
    /// Invalid swap amount error
    ///
    /// This error occurs when a swap amount is invalid (zero or below minimum).
    ///
    /// # When This Error Occurs
    ///
    /// - Swap amount is zero
    /// - Swap amount is below MIN_SWAP_AMOUNT (1)
    /// - Amount validation fails
    ///
    /// # How to Fix
    ///
    /// - Ensure swap amount is >= MIN_SWAP_AMOUNT (1)
    /// - Check that amount is not zero
    /// - Verify amount is in the correct units (token's smallest unit)
    ///
    /// # Constraints
    ///
    /// - Minimum amount: MIN_SWAP_AMOUNT (1)
    /// - Must be expressed in token's smallest unit
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// // This will cause InvalidAmount error
    /// SwapParams { amount: 0, ... }
    ///
    /// // This is correct
    /// SwapParams { amount: 1000, ... }
    /// ```
    #[msg("Invalid swap amount (must be > 0)")]
    InvalidAmount,
    
    /// Swap failed error
    ///
    /// This error occurs when a swap operation fails for an unspecified reason.
    /// This is a generic error that should be replaced with more specific errors
    /// as the program is developed.
    ///
    /// # When This Error Occurs
    ///
    /// - Swap execution fails
    /// - Swap validation fails after initial checks
    /// - Generic swap failure
    ///
    /// # How to Fix
    ///
    /// - Check swap parameters
    /// - Verify account states
    /// - Check network conditions
    ///
    /// # Future Enhancements
    ///
    /// This error should be replaced with more specific errors as the program
    /// is developed and more swap logic is implemented.
    #[msg("Swap failed")]
    SwapFailed,
    
    /// Invalid swap pair error
    ///
    /// This error occurs when a swap is attempted with the same input and
    /// output mint (i.e., swapping a token for itself).
    ///
    /// # When This Error Occurs
    ///
    /// - Input mint equals output mint
    /// - User attempts to swap a token for itself
    ///
    /// # How to Fix
    ///
    /// - Ensure input_mint != output_mint
    /// - Check that mints are different tokens
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// // This will cause InvalidSwapPair error
    /// SwapParams {
    ///     input_mint: sol_mint,
    ///     output_mint: sol_mint,  // Same mint!
    ///     ...
    /// }
    ///
    /// // This is correct
    /// SwapParams {
    ///     input_mint: sol_mint,
    ///     output_mint: usdc_mint,  // Different mints
    ///     ...
    /// }
    /// ```
    #[msg("Invalid swap pair (input and output mints must differ)")]
    InvalidSwapPair,
    
    /// Invalid minimum output amount error
    ///
    /// This error occurs when the minimum output amount is invalid (zero or negative).
    ///
    /// # When This Error Occurs
    ///
    /// - Minimum output amount is zero
    /// - Minimum output amount is negative (shouldn't happen with u64, but validated)
    /// - Minimum output amount validation fails
    ///
    /// # How to Fix
    ///
    /// - Ensure min_output_amount > 0
    /// - Check that amount is in the correct units
    /// - Verify amount accounts for expected slippage
    ///
    /// # Constraints
    ///
    /// - Minimum output amount must be > 0
    /// - Should account for slippage (e.g., 5% slippage tolerance)
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// // This will cause InvalidMinOutput error
    /// SwapParams { min_output_amount: 0, ... }
    ///
    /// // This is correct
    /// SwapParams { min_output_amount: 90_000_000, ... }
    /// ```
    #[msg("Invalid minimum output amount")]
    InvalidMinOutput,
    
    /// Invalid account error
    ///
    /// This error occurs when an account is invalid or doesn't meet the
    /// required constraints.
    ///
    /// # When This Error Occurs
    ///
    /// - Account is not a valid token account
    /// - Account doesn't exist
    /// - Account doesn't meet required constraints
    ///
    /// # How to Fix
    ///
    /// - Verify account exists
    /// - Check account type (must be token account)
    /// - Verify account constraints
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// // This will cause InvalidAccount error if account is invalid
    /// // Check that account is a valid token account
    /// ```
    #[msg("Invalid account")]
    InvalidAccount,
    
    /// Account mint mismatch error
    ///
    /// This error occurs when token accounts have different mints when
    /// they should have the same mint (e.g., in a token transfer).
    ///
    /// # When This Error Occurs
    ///
    /// - Source and destination accounts have different mints
    /// - Attempting to transfer between incompatible token accounts
    ///
    /// # How to Fix
    ///
    /// - Ensure source and destination accounts have the same mint
    /// - Check that accounts are for the same token type
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// // This will cause InvalidAccountMismatch error
    /// // if from.mint != to.mint
    /// execute_swap(ctx, amount)?;
    ///
    /// // Ensure both accounts are for the same token
    /// ```
    #[msg("Account mint mismatch")]
    InvalidAccountMismatch,
    
    /// Invalid authority error
    ///
    /// This error occurs when the authority doesn't have the required
    /// permissions to execute an operation.
    ///
    /// # When This Error Occurs
    ///
    /// - Authority doesn't own the source token account
    /// - Authority doesn't have required permissions
    /// - Authority validation fails
    ///
    /// # How to Fix
    ///
    /// - Ensure authority owns the source token account
    /// - Verify authority has required permissions
    /// - Check that authority is the correct signer
    ///
    /// # Security
    ///
    /// This error is critical for security. It ensures that only the
    /// owner of tokens can transfer them.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// // This will cause InvalidAuthority error
    /// // if authority doesn't own the from account
    /// execute_swap(ctx, amount)?;
    ///
    /// // Ensure authority is the owner of the source account
    /// ```
    #[msg("Invalid authority (must be token account owner)")]
    InvalidAuthority,
    
    /// Token transfer failed error
    ///
    /// This error occurs when a token transfer fails during execution.
    /// This could be due to insufficient balance, account state, or
    /// other transfer-related issues.
    ///
    /// # When This Error Occurs
    ///
    /// - Insufficient balance in source account
    /// - Destination account is frozen
    /// - Transfer authorization fails
    /// - SPL Token program returns an error
    ///
    /// # How to Fix
    ///
    /// - Ensure source account has sufficient balance
    /// - Check that destination account is not frozen
    /// - Verify transfer authorization
    /// - Check account states
    ///
    /// # Common Causes
    ///
    /// - Insufficient balance: Source account doesn't have enough tokens
    /// - Frozen account: Destination account is frozen
    /// - Authorization: Transfer authority is not set correctly
    /// - Account state: Account is in an invalid state
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// // This will cause TransferFailed error if transfer fails
    /// execute_swap(ctx, amount)?;
    ///
    /// // Check:
    /// // - Source account has sufficient balance
    /// // - Destination account is not frozen
    /// // - Transfer authorization is correct
    /// ```
    #[msg("Token transfer failed")]
    TransferFailed,
    
    /// Slippage tolerance exceeded error
    ///
    /// This error occurs when the actual output amount from a swap is less
    /// than the minimum output amount specified (slippage tolerance exceeded).
    ///
    /// # When This Error Occurs
    ///
    /// - Actual output < min_output_amount after swap execution
    /// - Price moved unfavorably during swap execution
    /// - Insufficient liquidity causing worse execution price
    ///
    /// # How to Fix
    ///
    /// - Increase slippage tolerance
    /// - Reduce swap amount
    /// - Wait for better market conditions
    /// - Check liquidity availability
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// // If min_output_amount is 95 and actual output is 94, this error occurs
    /// ```
    #[msg("Slippage tolerance exceeded")]
    SlippageExceeded,
    
    /// Insufficient output amount error
    ///
    /// This error occurs when the actual output amount is less than the
    /// minimum required output amount after accounting for fees.
    ///
    /// # When This Error Occurs
    ///
    /// - Output amount after fees < min_output_amount
    /// - Fees exceed expected output
    /// - Swap execution resulted in insufficient output
    ///
    /// # How to Fix
    ///
    /// - Adjust min_output_amount to account for fees
    /// - Increase input amount
    /// - Check fee structure
    #[msg("Insufficient output amount")]
    InsufficientOutput,
    
    /// Invalid fee recipient error
    ///
    /// This error occurs when a fee recipient account is provided but
    /// is invalid or incompatible with the fee token.
    ///
    /// # When This Error Occurs
    ///
    /// - Fee recipient account has wrong mint
    /// - Fee recipient account is invalid
    /// - Fee recipient account cannot receive fees
    ///
    /// # How to Fix
    ///
    /// - Provide correct fee recipient account
    /// - Ensure fee recipient has correct mint
    /// - Verify fee recipient account is valid
    #[msg("Invalid fee recipient")]
    InvalidFeeRecipient,
    
    /// Swap execution failed error
    ///
    /// This error occurs when a swap execution fails for an unspecified reason.
    /// This is a generic error for swap execution failures.
    ///
    /// # When This Error Occurs
    ///
    /// - DEX swap execution fails
    /// - Jupiter integration fails
    /// - Swap routing fails
    /// - Generic swap execution failure
    ///
    /// # How to Fix
    ///
    /// - Check swap parameters
    /// - Verify account states
    /// - Check DEX availability
    /// - Verify routing parameters
    #[msg("Swap execution failed")]
    SwapExecutionFailed,
    
    /// Price impact too high error
    ///
    /// This error occurs when the price impact of a swap exceeds acceptable limits.
    ///
    /// # When This Error Occurs
    ///
    /// - Price impact > maximum allowed
    /// - Swap would cause significant price movement
    /// - Insufficient liquidity for swap size
    ///
    /// # How to Fix
    ///
    /// - Reduce swap amount
    /// - Split into smaller swaps
    /// - Wait for better liquidity
    #[msg("Price impact too high")]
    PriceImpactTooHigh,

    /// Math overflow error
    ///
    /// This error occurs when a mathematical operation results in overflow or underflow.
    /// This is a security-critical error that prevents integer overflow/underflow vulnerabilities.
    ///
    /// # When This Error Occurs
    ///
    /// - Addition results in overflow
    /// - Multiplication results in overflow
    /// - Subtraction results in underflow
    /// - Division by zero
    ///
    /// # How to Fix
    ///
    /// - Use safe math operations
    /// - Validate inputs before calculations
    /// - Check for edge cases
    #[msg("Math overflow or underflow")]
    MathOverflow,

    /// Insufficient funds error
    ///
    /// This error occurs when an account doesn't have sufficient balance for an operation.
    ///
    /// # When This Error Occurs
    ///
    /// - Account balance < required amount
    /// - Token account balance < required amount
    /// - Insufficient SOL for transaction fees
    ///
    /// # How to Fix
    ///
    /// - Ensure account has sufficient balance
    /// - Check balance before executing operation
    /// - Add more funds to account
    #[msg("Insufficient funds")]
    InsufficientFunds,
}


